/* Stream Deck Control tools. UI only: the host's dispatcher owns every live command. */
(function (global) {
  'use strict';
  const STRINGS = {
    en: {
      title:'STREAM DECK', optional:'Optional · manual profile activation', setup:'Set up integration', install:'Install / update plugin', enable:'Enable connection', device:'Stream Deck device', noDevice:'No connected device', activate:'Activate ProTimer profile', back:'Return / deactivate', edit:'Edit layout', profile:'Starter profile', standard:'Standard 28 + 4 free', full:'Full 32',
      manual:'Connecting does not switch profiles, start a timer or open an output. Choose your profile manually in Elgato, then place and link ProTimer Key actions.', unverified:'Bundled profiles have not been verified in this build. Add ProTimer Key actions in the Elgato editor; automatic starter-profile activation is unavailable.', profileUnknown:'Profile identity cannot be confirmed. Only visible ProTimer actions can be observed; other apps and profiles remain private.',
      disabled:'Integration disabled', 'no-software':'Stream Deck software not found', pairing:'Waiting for pairing', 'plugin-missing':'Plugin is not responding', 'no-device':'No connected Stream Deck', connected:'Connected', outdated:'Plugin update required', 'profile-inactive':'No visible ProTimer actions — profile identity unknown', stale:'STALE — connection needs refreshing', unknown:'Not checked yet',
      target:'Target timer', t1:'Timer 1', t2:'Timer 2', selected:'Selected timer', set:'SET · prepared', live:'LIVE · active time', active:'ACTIVE', prepared:'SET', enterTime:'Enter SET time', startSet:'START SET', liveNotice:'LIVE adjustments affect the running timer. Presets still change SET only.', setNotice:'SET can be prepared without changing ACTIVE. START SET is the separate, explicit start.',
      editor:'Stream Deck layout', editorHint:'EDITING ONLY · clicking a key never executes it', layoutName:'Layout name', saveName:'Save named layout', saved:'Saved layouts', load:'Load', undo:'Undo', redo:'Redo', defaults:'Restore defaults', import:'Import JSON', export:'Export JSON', cancel:'Cancel', apply:'Apply layout', close:'Close', choose:'Select a key to edit', command:'Command', name:'Custom label', automatic:'Automatic label', color:'Accent color', icon:'Built-in icon', textSize:'Text size', stateDisplay:'Show state and T1/T2', keyTarget:'Timer target', editTarget:'Adjustment target', step:'Signed step', unit:'Unit', hours:'Hours', minutes:'Minutes', seconds:'Seconds', preset:'Preset HH:MM:SS', hotkey:'Keyboard shortcut', hotkeyHelp:'Local unless global shortcuts are explicitly enabled. Example: Ctrl+Shift+1. Space is never global.', press:'Press rule', short:'Short press', hold:'Hold 1.5 seconds', confirm:'Confirm with a second press', move:'Move / swap with slot', moveDo:'Move', duplicate:'Duplicate', remove:'Empty ProTimer slot', free:'FREE', empty:'INACTIVE', slot:'Slot',
      freeHelp:'FREE is not a ProTimer action. To put a control here, first drag ProTimer Key onto this position in the Elgato editor. ProTimer cannot replace another plugin’s button.', ownedHelp:'An inactive ProTimer slot still belongs to our action and can be filled again here. To make it truly free for another plugin, remove the action in the Elgato editor.', inventoryHelp:'This is the logical ProTimer layout, not a scan of other plugins. Only our currently visible action instances are reported by the SDK.', unknownSlot:'Device ownership not confirmed', knownSlot:'ProTimer action visible on selected device', keysHelp:'Drag to move or swap. Keyboard: arrow keys select a slot; use Move for accessible reordering. Changes remain here until Apply.', overrideHelp:'A title or icon set manually in Elgato takes priority. Reset that override in Elgato to restore ProTimer’s live LCD display.',
      simulation:'SIMULATION · NEVER SENT TO TIMER', simulate:'Preview selected key', simulationHint:'Preview uses fixed sample values. It cannot start, reset, change an output or play sound.', simulated:'Sample only', duplicateHotkey:'Duplicate shortcut', noFree:'No empty slot is available. Empty a ProTimer slot first.', changed:'Unsaved editor changes', noChanges:'No editor changes', applied:'Layout saved in ProTimer.', deviceConfirmed:'Plugin confirmed its visible ProTimer actions.', devicePending:'Device application is not confirmed. No hardware result is being claimed.', appliedFailed:'The layout was not applied.', savedOk:'Named layout saved. Other saved layouts were kept.', imported:'JSON loaded into the editor. Apply is still required.', exported:'Validated JSON exported without connection secrets.', invalid:'Invalid layout', tooLarge:'Layout file is too large (maximum 100 KB).', ready:'Ready', error:'Operation failed', busy:'Working…', pending:'Confirmation required — press again', cancelConfirm:'Cancel confirmation', numeric:'Enter prepared time', numericHint:'Only SET changes. ACTIVE keeps running. Select hours, minutes or seconds, then enter digits.', applySet:'Apply to SET', backspace:'Backspace', clear:'Clear entry', clearSet:'Clear SET', numericAll:'All fields', numericActive:'ACTIVE continues',
      audio:'Bell audio', sound:'Sound', defaultBell:'Built-in bell', localSound:'Selected local sound', defaultOutput:'System default (explicit choice)', chooseSound:'Choose local sound…', volume:'Volume', audioOutput:'Audio output', refreshAudio:'Refresh audio outputs', audioSave:'Save audio settings', audioTest:'Play test bell', audioHint:'Manual test only. One bell at a time; repeat presses do not overlap. A missing chosen output must be resolved before playback.', global:'Enable global shortcuts', globalHint:'Global shortcuts are optional. Protected actions use confirmation, because OS APIs cannot reliably report key release. Conflicts are reported, never silently ignored.', settings:'Audio and shortcuts', saveSettings:'Save settings', disabledTimer:'Timer 2 is disabled. Enable it in the existing Two timers controls.',
      layoutTools:'Layout name, saved layouts and JSON', holdPolicyHelp:'Physical Deck: protected actions always require a 1.5-second hold. Keyboard confirmation uses a second local press or a native global-shortcut dialog.', keyboardConfirm:'Keyboard confirmation · hold on Deck', globalDialogHelp:'All global shortcuts use an explicit dialog; held-key repeats cannot confirm an action. Local protected shortcuts use a second deliberate press.', bindAction:'Existing ProTimer Key on device', bind:'Connect this slot', bindHint:'First add ProTimer Key in Elgato. Choose that visible action here and connect it to this logical slot. Other plugins are never listed or modified.', bindSaved:'Apply this layout before connecting a new slot.', noOwnActions:'No visible ProTimer actions', identities:'Advanced slot identity', bound:'Slot link confirmed by the plugin.',
      noAdapter:'This action is not available in this build.', noModel:'The layout validator is unavailable. Editing is disabled.', offline:'OFFLINE', defaultsHint:'Defaults replace only this editor draft. Named layouts are preserved.', importHint:'Only a validated ProTimer layout is accepted. No tokens, scripts, shell commands or arbitrary images are imported.', none:'None', acknowledge:'OK', local:'Local', source:'Source',
    },
    sr: {
      title:'STREAM DECK', optional:'Opciono · ručno aktiviranje profila', setup:'Podesi integraciju', install:'Instaliraj / ažuriraj plugin', enable:'Uključi povezivanje', device:'Stream Deck uređaj', noDevice:'Nema povezanog uređaja', activate:'Aktiviraj ProTimer profil', back:'Vrati profil / deaktiviraj', edit:'Uredi raspored', profile:'Početni profil', standard:'Standard 28 + 4 slobodna', full:'Svih 32',
      manual:'Povezivanje ne menja profil, ne pokreće tajmer i ne otvara izlaz. Ručno izaberi profil u Elgato aplikaciji, zatim postavi i poveži ProTimer Key akcije.', unverified:'Početni profili u ovom izdanju nisu potvrđeni u Elgato aplikaciji. Dodaj ProTimer Key akcije u Elgato editoru; aktiviranje početnog profila nije dostupno.', profileUnknown:'Identitet profila nije potvrđen. Vidimo samo naše prikazane akcije; drugi programi i profili ostaju privatni.',
      disabled:'Integracija je isključena', 'no-software':'Stream Deck softver nije pronađen', pairing:'Čeka uparivanje', 'plugin-missing':'Plugin se ne javlja', 'no-device':'Nema povezanog Stream Deck uređaja', connected:'Povezano', outdated:'Potrebno je ažurirati plugin', 'profile-inactive':'Nema vidljivih ProTimer akcija — identitet profila nije poznat', stale:'STALE — potrebno je obnoviti vezu', unknown:'Još nije provereno',
      target:'Ciljni tajmer', t1:'Tajmer 1', t2:'Tajmer 2', selected:'Izabrani tajmer', set:'SET · pripremljeno', live:'LIVE · aktivno vreme', active:'ACTIVE', prepared:'SET', enterTime:'Unesi SET vreme', startSet:'START SET', liveNotice:'LIVE korekcije menjaju aktivni tajmer. Preseti i dalje menjaju samo SET.', setNotice:'Pripremaj SET bez promene ACTIVE vremena. START SET je zasebno, namerno pokretanje.',
      editor:'Stream Deck raspored', editorHint:'SAMO UREĐIVANJE · klik na dugme ga ne izvršava', layoutName:'Naziv rasporeda', saveName:'Sačuvaj pod nazivom', saved:'Sačuvani rasporedi', load:'Učitaj', undo:'Poništi', redo:'Ponovi', defaults:'Početni raspored', import:'Uvezi JSON', export:'Izvezi JSON', cancel:'Otkaži', apply:'Primeni raspored', close:'Zatvori', choose:'Izaberi dugme za uređivanje', command:'Komanda', name:'Tvoj natpis', automatic:'Automatski natpis', color:'Boja oznake', icon:'Ugrađena ikona', textSize:'Veličina teksta', stateDisplay:'Prikaži status i T1/T2', keyTarget:'Ciljni tajmer', editTarget:'Cilj korekcije', step:'Korak sa + ili −', unit:'Jedinica', hours:'Sati', minutes:'Minuti', seconds:'Sekunde', preset:'Preset HH:MM:SS', hotkey:'Prečica na tastaturi', hotkeyHelp:'Lokalna, osim ako izričito uključiš globalne prečice. Primer: Ctrl+Shift+1. Space nije globalan.', press:'Pravilo pritiska', short:'Kratak pritisak', hold:'Držanje 1,5 sekundi', confirm:'Potvrda drugim pritiskom', move:'Premesti / zameni sa mestom', moveDo:'Premesti', duplicate:'Dupliraj', remove:'Isprazni ProTimer mesto', free:'SLOBODNO', empty:'NEAKTIVNO', slot:'Mesto',
      freeHelp:'SLOBODNO nije ProTimer akcija. Za novu komandu prvo prevuci ProTimer Key na ovo mesto u Elgato editoru. ProTimer ne može da zameni dugme drugog plugina.', ownedHelp:'Neaktivno ProTimer mesto i dalje sadrži našu akciju i ovde možeš da ga popuniš. Za stvarno slobodno dugme ukloni akciju u Elgato editoru.', inventoryHelp:'Ovo je logički ProTimer raspored, ne pregled drugih plugina. SDK prijavljuje samo naše trenutno vidljive akcije.', unknownSlot:'Vlasništvo na uređaju nije potvrđeno', knownSlot:'ProTimer akcija je vidljiva na izabranom uređaju', keysHelp:'Prevuci za premeštanje ili zamenu. Tastatura: strelice biraju mesto; opcija Premesti menja raspored. Ništa se ne primenjuje pre klika Primeni.', overrideHelp:'Natpis ili slika koje ručno postaviš u Elgato editoru imaju prednost. Ukloni taj ručni izbor u Elgato editoru da vratiš ProTimer live LCD prikaz.',
      simulation:'SIMULACIJA · NE ŠALJE SE TAJMERU', simulate:'Pregled izabranog dugmeta', simulationHint:'Pregled koristi fiksne primere. Ne može da pokrene ili resetuje tajmer, promeni izlaz ili pusti zvuk.', simulated:'Samo primer', duplicateHotkey:'Duplirana prečica', noFree:'Nema praznog mesta. Prvo isprazni ProTimer mesto.', changed:'Izmene još nisu primenjene', noChanges:'Nema izmena u editoru', applied:'Raspored je sačuvan u ProTimeru.', deviceConfirmed:'Plugin je potvrdio svoje vidljive ProTimer akcije.', devicePending:'Primena na uređaju nije potvrđena. Ovo nije potvrda fizičkog uređaja.', appliedFailed:'Raspored nije primenjen.', savedOk:'Raspored je sačuvan pod nazivom. Drugi sačuvani rasporedi su zadržani.', imported:'JSON je učitan u editor. Još treba kliknuti Primeni.', exported:'Izvezen je validiran JSON bez tajnih podataka za povezivanje.', invalid:'Neispravan raspored', tooLarge:'Datoteka je prevelika (maksimum 100 KB).', ready:'Spremno', error:'Radnja nije uspela', busy:'Sačekaj…', pending:'Potrebna je potvrda — pritisni ponovo', cancelConfirm:'Otkaži potvrdu', numeric:'Unesi pripremljeno vreme', numericHint:'Menja se samo SET. ACTIVE nastavlja da radi. Izaberi sate, minute ili sekunde, pa unesi cifre.', applySet:'Primeni u SET', backspace:'Obriši cifru', clear:'Očisti unos', clearSet:'Obriši SET', numericAll:'Sva polja', numericActive:'ACTIVE nastavlja',
      audio:'Zvonce', sound:'Zvuk', defaultBell:'Ugrađeno zvonce', localSound:'Izabrani lokalni zvuk', defaultOutput:'Sistemski izlaz (izričit izbor)', chooseSound:'Izaberi lokalni zvuk…', volume:'Jačina', audioOutput:'Audio izlaz', refreshAudio:'Osveži audio izlaze', audioSave:'Sačuvaj zvuk', audioTest:'Ručno probaj zvonce', audioHint:'Samo ručna proba. Jedno zvonce u datom trenutku; ponovni pritisci se ne preklapaju. Ako odabrani izlaz nestane, prvo treba rešiti izlaz.', global:'Uključi globalne prečice', globalHint:'Globalne prečice su opcione. Za zaštićene radnje koristi se potvrda, jer OS ne javlja pouzdano puštanje tastera. Konflikti se prijavljuju.', settings:'Zvuk i prečice', saveSettings:'Sačuvaj podešavanja', disabledTimer:'Tajmer 2 je isključen. Uključi ga postojećom kontrolom Dva tajmera.',
      layoutTools:'Naziv, sačuvani rasporedi i JSON', holdPolicyHelp:'Fizički Deck: zaštićene radnje uvek traže držanje 1,5 sekundi. Tastatura koristi drugu lokalnu potvrdu ili dijalog za globalnu prečicu.', keyboardConfirm:'Potvrda tastaturom · držanje na Decku', globalDialogHelp:'Sve globalne prečice traže izričitu potvrdu u dijalogu; ponavljanje držanog tastera nije potvrda. Zaštićene lokalne prečice koriste drugi namerni pritisak.', bindAction:'Postojeći ProTimer Key na uređaju', bind:'Poveži ovo mesto', bindHint:'Prvo dodaj ProTimer Key u Elgato editoru. Zatim ovde izaberi tu vidljivu akciju i poveži je sa ovim mestom rasporeda. Drugi plugini se ne prikazuju i ne menjaju.', bindSaved:'Pre povezivanja novog mesta primeni raspored.', noOwnActions:'Nema vidljivih ProTimer akcija', identities:'Napredni identitet mesta', bound:'Plugin je potvrdio povezivanje mesta.',
      noAdapter:'Ova radnja nije dostupna u ovom izdanju.', noModel:'Validator rasporeda nije dostupan. Uređivanje je isključeno.', offline:'OFFLINE', defaultsHint:'Početni raspored menja samo nacrt u editoru. Sačuvani rasporedi ostaju.', importHint:'Prihvata se samo proveren ProTimer raspored. Ne uvoze se tokeni, skripte, shell komande ili proizvoljne slike.', none:'Bez', acknowledge:'U redu', local:'Lokalno', source:'Izvor',
    },
  };
  const ICONS = {none:'',play:'▶',pause:'Ⅱ',clock:'◷',timer:'◴',plus:'＋',minus:'−',reset:'↺',bell:'♧',screen:'▣',message:'▤',settings:'⚙',back:'↶',edit:'✎',stop:'■',grid:'▦',up:'↑',down:'↓',left:'←',right:'→',lock:'◆'};
  const DISPLAY_COMMANDS = new Set(['activeTime','setTime','empty']);
  const GUARDED = new Set(['reset','blackout','startSet']);
  const clone = value => JSON.parse(JSON.stringify(value));
  const randomId = () => global.crypto?.randomUUID?.() || ('key-' + Date.now().toString(36) + '-' + Math.random().toString(36).slice(2));
  function node(tag, className, text) { const n=document.createElement(tag); if(className)n.className=className; if(text!==undefined)n.textContent=String(text); return n; }
  function button(text, fn, className='') { const n=node('button',className,text);n.type='button';if(fn)n.addEventListener('click',fn);return n; }
  function options(select, values, selected) { select.replaceChildren(...values.map(([value,label])=>{const n=node('option','',label);n.value=value;return n;}));select.value=selected??values[0]?.[0]??''; }
  function mount(host, adapter={}) {
    if(!host || typeof host.replaceChildren!=='function')throw new TypeError('A Stream Deck host element is required');
    const L=global.DeckLayout || global.ProTimerDeckLayout;
    let language=adapter.lang==='en'?'en':'sr', snapshot={}, editor=null, numeric=null, settings=null, destroyed=false;
    const t=k=>STRINGS[language][k]||STRINGS.en[k]||k;
    const fmt=ms=>global.DeckModel?.formatTime?.(ms) || (()=>{const seconds=Math.ceil(Math.abs(Number(ms)||0)/1000),h=Math.floor(seconds/3600),m=Math.floor(seconds/60)%60,s=seconds%60;return (ms<0?'−':'')+(h?h+':'+String(m).padStart(2,'0'):String(m))+':'+String(s).padStart(2,'0');})();
    const field=(parent,label,input)=>{const wrap=node('label','',label);wrap.append(input);parent.append(wrap);return input;};
    const makeSelect=(parent,label,values,selected,onchange)=>{const n=node('select');options(n,values,selected);if(onchange)n.addEventListener('change',()=>onchange(n.value));field(parent,label,n);return n;};
    const feedback=node('p','pt-deck-feedback');feedback.setAttribute('role','status');feedback.setAttribute('aria-live','polite');
    function say(message,error=false,where=feedback){where.textContent=message||'';where.dataset.error=String(error);}
    async function invoke(action,payload={},where=feedback){
      if(destroyed)return {ok:false};
      try{if(typeof adapter.invoke!=='function')throw Error(t('noAdapter'));const result=await adapter.invoke(action,payload);if(result?.snapshot)update(result.snapshot);if(result?.ok===false){say(result.code==='CONFIRM_REQUIRED'?t('pending'):result.reason||result.message||result.error||t('error'),result.code!=='CONFIRM_REQUIRED',where);return result;}return result??{ok:true};}
      catch(error){say(error?.message||t('error'),true,where);return {ok:false};}
    }
    function timerId(){return snapshot.selectedTimerId==='t2'?'t2':'t1';}
    function timerData(id=timerId()){return snapshot.timers?.[id]||{active:{},draft:{}};}
    function command(type,args={},where=feedback){const {timerId:id=timerId(),expectedActiveVersion,expectedDraftVersion,...payload}=args;if(type==='selectTimer')payload.timerId=id;if(type==='numericDigit')payload.digit=Number(payload.digit);const cmd={type,timerId:id,commandId:randomId(),payload};if(expectedActiveVersion!==undefined)cmd.expectedActiveVersion=expectedActiveVersion;if(expectedDraftVersion!==undefined)cmd.expectedDraftVersion=expectedDraftVersion;return invoke('command',cmd,where).then(r=>{if(r.confirmationRequired||r.code==='CONFIRM_REQUIRED')say(t('pending'),false,where);return r;});}
    const section=node('section','pt-deck card');const details=node('details');const summary=node('summary');const head=node('div');const title=node('h3');const sub=node('p','pt-deck-help');head.append(title,sub);summary.append(head);details.append(summary);section.append(details);host.replaceChildren(section);
    const body=node('div','pt-deck-body');details.append(body);
    const status=node('div','pt-deck-status');status.setAttribute('role','status');body.append(status);
    const statusDetail=node('p','pt-deck-help');body.append(statusDetail);
    const enabledLabel=node('label','pt-deck-check');const enabled=node('input');enabled.type='checkbox';const enabledText=node('span');enabledLabel.append(enabled,enabledText);body.append(enabledLabel);enabled.addEventListener('change',async()=>{const wanted=enabled.checked;enabled.disabled=true;await invoke('enable',{enabled:wanted});enabled.disabled=false;enabled.checked=!!snapshot.enabled;});
    const setupActions=node('div','pt-deck-actions');const setup=button('',()=>invoke('setup'));const install=button('',()=>invoke('install'));setupActions.append(setup,install);body.append(setupActions);
    const deviceLabel=node('label');const deviceText=node('span');const device=node('select');deviceLabel.append(deviceText,device);body.append(deviceLabel);device.addEventListener('change',()=>invoke('selectDevice',{deviceId:device.value}));
    const profileLabel=node('label');const profileText=node('span');const profile=node('select');profileLabel.append(profileText,profile);body.append(profileLabel);
    const activate=button('',()=>invoke('activate',{deviceId:device.value,profile:profile.value}),'primary');const back=button('',()=>invoke('back',{deviceId:device.value}));body.append(activate,back);
    const profileWarning=node('p','pt-deck-help');body.append(profileWarning);
    const manual=node('p','pt-deck-help');body.append(manual);
    const editorButton=button('',()=>openEditor());const settingsButton=button('',()=>openSettings());const editRow=node('div','pt-deck-actions');editRow.append(editorButton,settingsButton);body.append(editRow);
    const readouts=node('div','pt-deck-live');
    function createReadout(kind){const box=node('div','pt-deck-readout');box.dataset.kind=kind;const label=node('span'),value=node('strong','', '—'),state=node('small');box.append(label,value,state);readouts.append(box);return{box,label,value,state};}
    const activeReadout=createReadout('active'),setReadout=createReadout('set');body.append(readouts);
    const timerLabel=node('label');const timerText=node('span');const timerSelect=node('select');timerLabel.append(timerText,timerSelect);body.append(timerLabel);timerSelect.addEventListener('change',()=>command('selectTimer',{timerId:timerSelect.value}));
    const liveTarget=node('p','pt-deck-help');body.append(liveTarget);
    const liveActions=node('div','pt-deck-actions');const enter=button('',()=>openNumeric());const start=button('',()=>command('startSet',expectedTimer()),'primary');liveActions.append(enter,start);body.append(liveActions,feedback);
    function expectedTimer(id=timerId()){const state=timerData(id);return {timerId:id,expectedDraftVersion:state.draft?.version,expectedActiveVersion:state.active?.version};}
    function renderStatic(){title.textContent=t('title');sub.textContent=t('optional');enabledText.textContent=t('enable');setup.textContent=t('setup');install.textContent=t('install');deviceText.textContent=t('device');profileText.textContent=t('profile');options(profile,[['standard',t('standard')],['full',t('full')]],profile.value||'standard');activate.textContent=t('activate');back.textContent=t('back');editorButton.textContent=t('edit');settingsButton.textContent=t('settings');manual.textContent=t('manual');timerText.textContent=t('target');options(timerSelect,[['t1',t('t1')],['t2',t('t2')]],timerId());enter.textContent=t('enterTime');start.textContent=t('startSet');editorButton.disabled=!L;}
    function paintReadouts(){const data=timerData(),id=timerId().toUpperCase(),a=data.active||{},d=data.draft||{};const stale=snapshot.stale===true;const state=stale?'STALE':a.status||'READY';activeReadout.label.textContent=id+' · ACTIVE';activeReadout.value.textContent=a.remainingMs===undefined&&a.elapsedMs===undefined?'—':fmt(a.mode==='countup'?a.elapsedMs:a.mode==='clock'?(a.clockMs??a.elapsedMs??0):a.remainingMs);activeReadout.state.textContent=state+' · '+(a.mode||'countdown').toUpperCase();activeReadout.box.dataset.status=state;setReadout.label.textContent=id+' · SET';setReadout.value.textContent=d.durationMs===undefined?'—':fmt(d.durationMs);setReadout.state.textContent=(d.status||'READY')+' · '+(d.mode||'countdown').toUpperCase();liveTarget.textContent=t(snapshot.editTarget==='live'?'liveNotice':'setNotice');liveTarget.style.color=snapshot.editTarget==='live'?'#edbf66':'';if(numeric)paintNumeric();}
    function update(next){if(destroyed)return;snapshot={...snapshot,...next};enabled.checked=!!snapshot.enabled;const state=snapshot.status||(!snapshot.enabled?'disabled':'unknown');status.dataset.state=state;status.textContent=t(state);statusDetail.textContent=snapshot.statusDetail||'';statusDetail.hidden=!statusDetail.textContent;const devices=(snapshot.devices||[]).map(d=>[String(d.id??d.deviceId),String(d.name??d.label??d.id??d.deviceId)]);const deviceKey=JSON.stringify(devices);if(device.dataset.options!==deviceKey){options(device,devices.length?devices:[['',t('noDevice')]],snapshot.selectedDeviceId);device.dataset.options=deviceKey;}if(snapshot.selectedDeviceId)device.value=snapshot.selectedDeviceId;device.disabled=!devices.length;activate.disabled=!(snapshot.canActivate===true&&snapshot.profilesVerified===true&&device.value);back.disabled=!(snapshot.profile?.canReturn===true&&device.value);profileWarning.textContent=snapshot.profilesVerified===false?t('unverified'):snapshot.profile?.known===false?t('profileUnknown'):'';profileWarning.hidden=!profileWarning.textContent;timerSelect.value=timerId();timerSelect.options[1].disabled=snapshot.timers?.t2?.active?.enabled===false;enter.disabled=!snapshot.timers;start.disabled=!snapshot.timers;paintReadouts();if(editor){paintEditorState();paintGrid();} }
    function makeDialog(heading,small=false){const dialog=node('dialog','pt-deck-dialog'+(small?' pt-deck-small':''));const header=node('header');const h=node('h2','',heading);h.id='pt-deck-dialog-'+randomId();dialog.setAttribute('aria-labelledby',h.id);const close=button(t('close'));header.append(h,close);const content=node('div','pt-deck-dialog-body');const footer=node('footer');dialog.append(header,content,footer);document.body.append(dialog);dialog.addEventListener('keydown',event=>{event.stopPropagation();});dialog.addEventListener('keyup',event=>event.stopPropagation());return{dialog,header,content,footer,close};}
    function valid(value){if(!L)throw Error(t('noModel'));const migrated=value?.schemaVersion===0&&typeof L.migrate==='function'?L.migrate(value):value;const r=L.validate(migrated);if(!r.ok)throw Error((r.errors||[t('invalid')]).map(e=>typeof e==='string'?e:e.message||String(e)).join('\n'));return r.layout;}
    function keyLabel(key){return key?L.label(key):t('free');}
    function openEditor(){if(editor){editor.dialog.focus();return;}if(!L){say(t('noModel'),true);return;}let layout;try{layout=valid(snapshot.layout||L.defaultLayout('standard'));}catch(error){say(error.message,true);return;}
      const modal=makeDialog(t('editor'));editor={...modal,history:L.createHistory?L.createHistory(layout):null,layout:clone(layout),original:JSON.stringify(layout),revision:snapshot.layoutRevision??0,selected:0,dirty:false,drag:null};
      const hint=node('p','pt-deck-help',t('editorHint'));modal.header.firstChild.append(node('small','pt-deck-help',''));modal.content.append(hint);
      const management=node('details','pt-deck-management');editor.managementSummary=node('summary','',t('layoutTools')+' · '+layout.name);management.append(editor.managementSummary);modal.content.append(management);
      const toolbar=node('div','pt-deck-toolbar');const name=node('input');name.type='text';name.maxLength=64;name.value=layout.name;editor.name=name;field(toolbar,t('layoutName'),name);name.addEventListener('change',()=>changeLayout(l=>{l.name=name.value;}));
      const save=button(t('saveName'),async()=>{let checked;try{checked=valid(editor.layout);}catch(e){say(e.message,true,editor.feedback);return;}const r=await invoke('saveLayout',{name:checked.name,layout:checked},editor.feedback);if(r.ok!==false)say(t('savedOk'),false,editor.feedback);});toolbar.append(save);management.append(toolbar);
      const tools=node('div','pt-deck-toolbar');editor.undo=button(t('undo'),()=>historyStep('undo'));editor.redo=button(t('redo'),()=>historyStep('redo'));const kind=node('select');options(kind,[['standard',t('standard')],['full',t('full')]],'standard');field(tools,t('profile'),kind);tools.append(button(t('defaults'),()=>{changeLayout(()=>L.defaultLayout(kind.value));say(t('defaultsHint'),false,editor.feedback);}));management.append(tools);
      const savedRow=node('div','pt-deck-toolbar');editor.saved=node('select');field(savedRow,t('saved'),editor.saved);savedRow.append(button(t('load'),()=>{const selected=(snapshot.savedLayouts||[]).find(l=>String(l.id)===editor.saved.value);if(selected?.layout||Array.isArray(selected?.slots))changeLayout(()=>valid(selected.layout||selected));else if(selected)invoke('loadLayout',{id:selected.id},editor.feedback).then(r=>{if(r.layout)changeLayout(()=>valid(r.layout));});}),button(t('import'),()=>importFile()),button(t('export'),()=>exportFile()));management.append(savedRow);
      const columns=node('div','pt-deck-editor-columns');const boardWrap=node('div','pt-deck-board-wrap');editor.grid=node('div','pt-deck-board');editor.grid.setAttribute('role','grid');editor.grid.setAttribute('aria-label','Stream Deck XL 8 × 4');editor.grid.setAttribute('aria-rowcount','4');editor.grid.setAttribute('aria-colcount','8');boardWrap.append(editor.grid,node('p','pt-deck-help',t('keysHelp')),node('p','pt-deck-help',t('inventoryHelp')));editor.inspector=node('div','pt-deck-inspector');columns.append(boardWrap,editor.inspector);modal.content.append(columns);
      const simulation=node('div','pt-deck-simulation');simulation.append(node('strong','',t('simulation')),node('p','pt-deck-help',t('simulationHint')));editor.simResult=node('div','pt-deck-previewresult');simulation.append(button(t('simulate'),simulateSelected),editor.simResult);boardWrap.append(simulation);modal.content.append(node('p','pt-deck-help',t('overrideHelp')));
      editor.feedback=node('p','pt-deck-feedback');editor.feedback.setAttribute('role','status');modal.content.append(editor.feedback);editor.dirtyState=node('span','pt-deck-help');const footerButtons=node('div','pt-deck-row');editor.apply=button(t('apply'),applyEditor,'primary');footerButtons.append(editor.undo,editor.redo,button(t('cancel'),closeEditor),editor.apply);modal.footer.append(editor.dirtyState,footerButtons);modal.close.addEventListener('click',closeEditor);modal.dialog.addEventListener('cancel',event=>{event.preventDefault();closeEditor();});
      paintEditorState();paintGrid();paintInspector();modal.dialog.showModal();editor.grid.children[0]?.focus();
    }
    function closeEditor(){if(!editor)return;const old=editor;editor=null;old.dialog.close();old.dialog.remove();editorButton.focus();}
    function changeLayout(mutate){if(!editor)return;try{const next=clone(editor.layout),replacement=mutate(next);const checked=valid(replacement||next);if(JSON.stringify(checked)===JSON.stringify(editor.layout))return;editor.history?.commit(checked);editor.layout=checked;editor.name.value=checked.name;paintGrid();paintInspector();paintEditorState();say('',false,editor.feedback);}catch(error){say(error.message,true,editor.feedback);}}
    function historyStep(op){if(!editor?.history)return;editor.history[op]();editor.layout=clone(editor.history.current());editor.name.value=editor.layout.name;paintGrid();paintInspector();paintEditorState();}
    function paintEditorState(){if(!editor)return;editor.dirty=JSON.stringify(editor.layout)!==editor.original;editor.dirtyState.textContent=t(editor.dirty?'changed':'noChanges');editor.managementSummary.textContent=t('layoutTools')+' · '+editor.layout.name;editor.undo.disabled=!editor.history?.canUndo();editor.redo.disabled=!editor.history?.canRedo();const saved=(snapshot.savedLayouts||[]).map(l=>[String(l.id),l.name||l.layout?.name||l.id]);const signature=JSON.stringify(saved);if(editor.saved.dataset.options!==signature){const selected=editor.saved.value;options(editor.saved,saved.length?saved:[['',t('none')]],selected);editor.saved.dataset.options=signature;}const duplicates=new Map();for(const key of editor.layout.slots){if(!key?.hotkey)continue;const accelerator=key.hotkey.trim().toLowerCase();duplicates.set(accelerator,(duplicates.get(accelerator)||0)+1);}editor.duplicateKeys=[...duplicates].filter(([,n])=>n>1).map(([key])=>key);editor.apply.disabled=editor.duplicateKeys.length>0;if(editor.duplicateKeys.length)say(t('duplicateHotkey')+': '+editor.duplicateKeys.join(', '),true,editor.feedback);}
    function paintBinding(){
      if(!editor?.bindSelect)return;
      const key=editor.layout.slots[editor.selected];if(!key)return;
      const own=(snapshot.inventory||[]).filter(item=>item.deviceId===snapshot.selectedDeviceId&&item.context);
      const entries=own.map(item=>[item.context,`${Number(item.row)+1}.${Number(item.column)+1} · ${item.slotId===key.id?'✓ ':''}${item.key?keyLabel(item.key):'ProTimer Key'}`]);
      const signature=JSON.stringify(entries),select=editor.bindSelect;
      if(select.dataset.options!==signature){const previous=select.value;options(select,entries.length?entries:[['',t('noOwnActions')]],own.some(item=>item.context===previous)?previous:own.find(item=>item.slotId===key.id&&item.layoutId===editor.layout.id)?.context);select.dataset.options=signature;}
      editor.bindButton.disabled=!own.length||JSON.stringify(editor.layout)!==editor.original;
      editor.bindHelp.textContent=t(editor.dirty?'bindSaved':'bindHint');
    }
    function knownOwned(index){const key=editor?.layout.slots[index];if(!key)return false;return (snapshot.inventory||[]).some(item=>String(item.deviceId??item.device??'')===String(snapshot.selectedDeviceId??'')&&(item.layoutId===editor.layout.id||item.settings?.layoutId===editor.layout.id)&&(item.slotId===key.id||item.settings?.slotId===key.id));}
    function paintGrid(){
      if(!editor)return;
      paintBinding();
      // Authoritative time ticks must not recreate keys during dragging or keyboard editing.
      const structure=JSON.stringify([editor.layout,editor.selected,language]);
      if(editor.gridStructure!==structure){
        editor.gridStructure=structure;
        const focused=document.activeElement,focusedIndex=focused?.parentElement===editor.grid?Number(focused.dataset.index):null;
        editor.grid.replaceChildren(...editor.layout.slots.map((key,index)=>{
          const n=button('');n.className='pt-deck-key'+(!key?' pt-deck-free':'');n.dataset.index=String(index);
          n.setAttribute('role','gridcell');n.setAttribute('aria-selected',String(index===editor.selected));
          n.setAttribute('aria-rowindex',String(Math.floor(index/8)+1));n.setAttribute('aria-colindex',String(index%8+1));
          n.tabIndex=index===editor.selected?0:-1;n.draggable=!!key;n.style.setProperty('--key-accent',key?.color||'#4775aa');
          n.append(node('span','pt-deck-key-position',`${Math.floor(index/8)+1}.${index%8+1}`));
          if(key){
            n.append(node('span','pt-deck-key-icon',ICONS[key.icon]||''));
            const label=node('span','pt-deck-key-name',key.command==='empty'?t('empty'):keyLabel(key));
            label.style.fontSize=Math.max(7,Math.min(15,key.textSize/1.8))+'px';n.append(label);
            if(key.command==='activeTime'||key.command==='setTime')n.append(node('span','pt-deck-key-time','—'));
            if(key.stateDisplay)n.append(node('span','pt-deck-key-meta',key.timerId==='selected'?'T1 / T2':key.timerId.toUpperCase()));
          }else n.append(node('span','pt-deck-key-name',t('free')));
          n.addEventListener('click',()=>selectKey(index));
          n.addEventListener('keydown',event=>{const shifts={ArrowLeft:-1,ArrowRight:1,ArrowUp:-8,ArrowDown:8};if(shifts[event.key]!==undefined){event.preventDefault();selectKey(Math.max(0,Math.min(31,index+shifts[event.key])));}});
          n.addEventListener('dragstart',event=>{editor.drag=index;event.dataTransfer.effectAllowed='move';event.dataTransfer.setData('text/plain',String(index));});
          n.addEventListener('dragover',event=>{if(editor.drag!==null){event.preventDefault();n.classList.add('pt-deck-drop');}});
          n.addEventListener('dragleave',()=>n.classList.remove('pt-deck-drop'));
          n.addEventListener('drop',event=>{event.preventDefault();const from=editor.drag;editor.drag=null;if(Number.isInteger(from)&&from!==index){changeLayout(l=>{[l.slots[from],l.slots[index]]=[l.slots[index],l.slots[from]];});selectKey(index);}});
          n.addEventListener('dragend',()=>{if(editor)editor.drag=null;});
          return n;
        }));
        if(focusedIndex!==null&&document.activeElement===document.body)editor.grid.children[focusedIndex]?.focus();
      }
      for(const [index,n] of [...editor.grid.children].entries()){
        const key=editor.layout.slots[index];n.title=keyLabel(key)+' — '+t(knownOwned(index)?'knownSlot':'unknownSlot');
        if(!key||!['activeTime','setTime'].includes(key.command))continue;
        const id=key.timerId==='selected'?timerId():key.timerId,data=timerData(id),prepared=key.command==='setTime';
        const millis=prepared?data.draft?.durationMs:data.active?.mode==='countup'?data.active?.elapsedMs:data.active?.mode==='clock'?data.active?.clockMs:data.active?.remainingMs;
        n.querySelector('.pt-deck-key-time').textContent=millis===undefined?'—':fmt(millis);
        const meta=n.querySelector('.pt-deck-key-meta');if(meta)meta.textContent=id.toUpperCase()+' · '+(prepared?(data.draft?.status||'READY'):(snapshot.stale?'STALE':data.active?.status||'READY'));
      }
    }
    function selectKey(index){if(!editor)return;editor.selected=index;paintGrid();paintInspector();editor.grid.children[index]?.focus();}
    function paintInspector(){if(!editor)return;const inspector=editor.inspector;inspector.replaceChildren();editor.bindSelect=null;const index=editor.selected,key=editor.layout.slots[index];inspector.append(node('h3','',t('slot')+' '+(index+1)+' · '+(key?keyLabel(key):t('free'))));
      if(!key)inspector.append(node('p','pt-deck-note pt-deck-warning',t('freeHelp')));else if(key.command==='empty')inspector.append(node('p','pt-deck-note',t('ownedHelp')));
      const commands=(L.catalog||[]).map(c=>typeof c==='string'?[c,c]:[c.id??c.command,c.label??c.name??c.id??c.command]);const current=key?.command||'';makeSelect(inspector,t('command'),[['',t('choose')],...commands],current,value=>{if(!value)return;changeLayout(l=>{const next=L.defaultKey(value);if(key)next.id=key.id;l.slots[index]=next;});});if(!key)return;
      const binding=makeSelect(inspector,t('bindAction'),[['',t('noOwnActions')]]);
      const bindButton=button(t('bind'),async()=>{const instance=(snapshot.inventory||[]).find(item=>item.context===binding.value&&item.deviceId===snapshot.selectedDeviceId);if(!instance)return;const result=await invoke('bindSlot',{context:instance.context,instanceId:instance.instanceId,deviceId:instance.deviceId,layoutId:editor.layout.id,slotId:key.id},editor.feedback);if(editor&&result.ok!==false)say(t(result.deviceConfirmed===true?'bound':'devicePending'),false,editor.feedback);});
      const bindHelp=node('p','pt-deck-help');editor.bindSelect=binding;editor.bindButton=bindButton;editor.bindHelp=bindHelp;inspector.append(bindButton,bindHelp);paintBinding();
      const identity=node('details');identity.append(node('summary','',t('identities')));const identityValue=node('input');identityValue.type='text';identityValue.readOnly=true;identityValue.value=editor.layout.id+' / '+key.id;identity.append(identityValue);inspector.append(identity);
      const change=(prop,value)=>changeLayout(l=>{l.slots[index][prop]=value;});
      const label=node('input');label.type='text';label.maxLength=28;label.value=key.name||'';label.placeholder=t('automatic');field(inspector,t('name'),label);label.addEventListener('change',()=>change('name',label.value));
      const color=node('input');color.type='color';color.value=key.color;field(inspector,t('color'),color);color.addEventListener('change',()=>change('color',color.value));
      const iconKeys=Array.isArray(L.icons)?L.icons:Object.keys(ICONS);makeSelect(inspector,t('icon'),iconKeys.map(v=>[v,(ICONS[v]?ICONS[v]+' ':'')+(v==='none'?t('none'):v)]),key.icon,value=>change('icon',value));
      const textSize=node('input');textSize.type='number';textSize.min='12';textSize.max='28';textSize.step='1';textSize.value=String(key.textSize);field(inspector,t('textSize'),textSize);textSize.addEventListener('change',()=>change('textSize',Number(textSize.value)));
      const stateLabel=node('label','pt-deck-check');const state=node('input');state.type='checkbox';state.checked=key.stateDisplay;stateLabel.append(state,node('span','',t('stateDisplay')));inspector.append(stateLabel);state.addEventListener('change',()=>change('stateDisplay',state.checked));
      makeSelect(inspector,t('keyTarget'),[['selected',t('selected')],['t1',t('t1')],['t2',t('t2')]],key.timerId,value=>change('timerId',value));
      if(key.command==='adjust'){makeSelect(inspector,t('editTarget'),[['selected',t('selected')],['set',t('set')],['live',t('live')]],key.target,value=>change('target',value));const step=node('input');step.type='number';step.min='-999';step.max='999';step.step='1';step.value=String(key.step);field(inspector,t('step'),step);step.addEventListener('change',()=>change('step',Number(step.value)));makeSelect(inspector,t('unit'),[['h',t('hours')],['m',t('minutes')],['s',t('seconds')]],key.unit,value=>change('unit',value));}
      if(key.command==='preset'){const preset=node('input');preset.type='text';preset.maxLength=8;preset.value=hms(key.durationMs);field(inspector,t('preset'),preset);preset.addEventListener('change',()=>{try{change('durationMs',parseDuration(preset.value));}catch(e){say(e.message,true,editor.feedback);}});}
      if(!DISPLAY_COMMANDS.has(key.command)){const hotkey=node('input');hotkey.type='text';hotkey.maxLength=64;hotkey.value=key.hotkey;hotkey.placeholder='Ctrl+Shift+1';field(inspector,t('hotkey'),hotkey);hotkey.addEventListener('change',()=>change('hotkey',hotkey.value.trim()));const choices=GUARDED.has(key.command)?[['hold',t('hold')],['confirm',t('keyboardConfirm')]]:[['short',t('short')],['hold',t('hold')],...(key.pressPolicy==='confirm'?[['confirm',t('keyboardConfirm')]]:[])];makeSelect(inspector,t('press'),choices,key.pressPolicy,value=>change('pressPolicy',value));if(GUARDED.has(key.command)||key.command==='editTarget')inspector.append(node('p','pt-deck-help',t('holdPolicyHelp')));}
      const move=node('select');options(move,editor.layout.slots.map((k,i)=>[String(i),`${i+1} · ${keyLabel(k)}`]),String(index));field(inspector,t('move'),move);const actions=node('div','pt-deck-row');actions.append(button(t('moveDo'),()=>{const to=Number(move.value);if(to!==index){changeLayout(l=>{[l.slots[index],l.slots[to]]=[l.slots[to],l.slots[index]];});selectKey(to);}}),button(t('duplicate'),()=>{let to=editor.layout.slots.findIndex((k,i)=>i!==index&&k?.command==='empty');if(to<0)to=editor.layout.slots.indexOf(null);if(to<0){say(t('noFree'),true,editor.feedback);return;}changeLayout(l=>{l.slots[to]={...clone(key),id:l.slots[to]?.id||randomId(),hotkey:''};});selectKey(to);}),button(t('remove'),()=>changeLayout(l=>{l.slots[index]={...L.defaultKey('empty'),id:key.id};}),'danger'));inspector.append(actions);
    }
    function hms(ms){const seconds=Math.floor(ms/1000);return[String(Math.floor(seconds/3600)).padStart(2,'0'),String(Math.floor(seconds/60)%60).padStart(2,'0'),String(seconds%60).padStart(2,'0')].join(':');}
    function parseDuration(value){if(!/^\d{1,2}:[0-5]\d:[0-5]\d$/.test(value))throw Error(t('preset')+' (00:00:00–99:59:59)');const [h,m,s]=value.split(':').map(Number);return(h*3600+m*60+s)*1000;}
    async function applyEditor(){if(!editor)return;const current=editor;let layout;try{layout=valid(current.layout);}catch(e){say(e.message,true,current.feedback);return;}current.apply.disabled=true;say(t('busy'),false,current.feedback);const result=await invoke('applyLayout',{layout,expectedRevision:current.revision},current.feedback);if(!editor||editor!==current)return;if(result.ok!==false&&result.applied===true){const applied=valid(result.layout||layout);current.original=JSON.stringify(applied);current.revision=result.layoutRevision??snapshot.layoutRevision??current.revision;current.layout=applied;current.name.value=applied.name;say(t('applied')+' '+t(result.deviceConfirmed===true?'deviceConfirmed':'devicePending'),false,current.feedback);}else if(result.ok!==false)say(t('appliedFailed'),true,current.feedback);paintEditorState();paintGrid();paintInspector();}
    async function importFile(){if(!editor)return;const input=node('input');input.type='file';input.accept='.json,application/json';input.hidden=true;editor.dialog.append(input);input.addEventListener('change',async()=>{const file=input.files?.[0];input.remove();if(!file)return;if(file.size>102400){say(t('tooLarge'),true,editor?.feedback);return;}try{const value=valid(JSON.parse(await file.text()));if(editor){changeLayout(()=>value);say(t('imported'),false,editor.feedback);}}catch(error){if(editor)say(t('invalid')+': '+error.message,true,editor.feedback);}});input.addEventListener('cancel',()=>input.remove());input.click();}
    async function exportFile(){if(!editor)return;let layout;try{layout=valid(editor.layout);}catch(e){say(e.message,true,editor.feedback);return;}const result=await invoke('exportLayoutFile',{layout},editor.feedback);if(result.ok!==false&&!result.canceled&&editor)say(t('exported'),false,editor.feedback);}
    function simulateSelected(){if(!editor)return;const key=editor.layout.slots[editor.selected];if(!key){editor.simResult.textContent=t('freeHelp');return;}const sample=key.command==='activeTime'?'T1 · 08:43 RUNNING':key.command==='setTime'?'T1 · 15:00 READY':key.command==='adjust'?`${keyLabel(key)} → ${key.target==='live'?'LIVE':'SET / '+t('selected')}`:key.command==='preset'?`SET → ${hms(key.durationMs)} READY`:key.command==='startSet'?'SET → ACTIVE · '+t('hold'):key.command==='bell'?t('simulated')+' · BELL ('+t('simulation')+')':keyLabel(key);editor.simResult.textContent=t('simulated')+': '+sample;}
    async function openNumeric(){if(numeric){numeric.dialog.focus();return;}const id=timerId();if(timerData(id).active?.enabled===false){say(t('disabledTimer'),true);return;}const result=await command('numericBegin',{timerId:id});if(result.ok===false)return;const modal=makeDialog(t('numeric'),true);numeric={...modal,timerId:id};const help=node('p','pt-deck-help',t('numericHint'));modal.content.append(help);numeric.active=node('p','pt-deck-help');modal.content.append(numeric.active);numeric.fields=node('div','pt-deck-number-fields');modal.content.append(numeric.fields);for(const fieldName of ['hours','minutes','seconds']){const b=button('',()=>command('numericField',{timerId:id,field:fieldName},numeric.feedback));b.dataset.field=fieldName;numeric.fields.append(b);}const keypad=node('div','pt-deck-keypad');for(const digit of [1,2,3,4,5,6,7,8,9])keypad.append(button(String(digit),()=>command('numericDigit',{timerId:id,digit:String(digit)},numeric.feedback)));keypad.append(button('⌫',()=>command('numericBackspace',{timerId:id},numeric.feedback)),button('0',()=>command('numericDigit',{timerId:id,digit:'0'},numeric.feedback)),button('C',()=>command('numericClear',{timerId:id},numeric.feedback)));keypad.children[9].setAttribute('aria-label',t('backspace'));keypad.children[11].setAttribute('aria-label',t('clear'));modal.content.append(keypad);numeric.feedback=node('p','pt-deck-feedback');numeric.feedback.setAttribute('role','status');modal.content.append(numeric.feedback);const buttons=node('div','pt-deck-row');buttons.append(button(t('cancel'),()=>closeNumeric(true)),button(t('applySet'),async()=>{const r=await command('numericApply',{timerId:id},numeric.feedback);if(r.ok!==false)closeNumeric(false);},'primary'));modal.footer.append(button(t('clearSet'),()=>command('clearSet',{timerId:id},numeric.feedback)),buttons);modal.close.addEventListener('click',()=>closeNumeric(true));modal.dialog.addEventListener('cancel',event=>{event.preventDefault();closeNumeric(true);});paintNumeric();modal.dialog.showModal();}
    function paintNumeric(){if(!numeric)return;const state=snapshot.numeric;const buffer=state?.timerId===numeric.timerId&&/^\d{6}$/.test(state.buffer)?state.buffer:'000000';const active=timerData(numeric.timerId).active;numeric.active.textContent=numeric.timerId.toUpperCase()+' · '+t('numericActive')+': '+fmt(active?.mode==='countup'?active.elapsedMs:active?.remainingMs)+' '+(active?.status||'READY');for(const [index,b] of [...numeric.fields.children].entries()){const fieldName=b.dataset.field;b.replaceChildren(document.createTextNode(buffer.slice(index*2,index*2+2)),node('small','',t(fieldName)));b.setAttribute('aria-pressed',String(state?.field===fieldName||state?.field==='all'));}}
    function closeNumeric(cancel){if(!numeric)return;const old=numeric;numeric=null;if(cancel)command('numericCancel',{timerId:old.timerId});old.dialog.close();old.dialog.remove();enter.focus();}
    async function openSettings(){if(settings){settings.dialog.focus();return;}const modal=makeDialog(t('settings'),true);settings={...modal};const current=settings,audio=snapshot.audio||{};modal.content.append(node('h3','',t('audio')));
      const sound=makeSelect(modal.content,t('sound'),[['builtin',t('defaultBell')],['file',t('localSound')]],audio.sound||'builtin');
      const soundName=node('p','pt-deck-help',audio.name||'');modal.content.append(soundName,button(t('chooseSound'),async()=>{const r=await invoke('audioChooseFile',{},current.feedback);if(r.ok!==false&&!r.canceled){sound.value='file';soundName.textContent=r.name||snapshot.audio?.name||t('localSound');}}));
      const volume=node('input');volume.type='range';volume.min='0';volume.max='100';volume.value=String(Math.round((audio.volume??.6)*100));field(modal.content,t('volume'),volume);const output=node('select');field(modal.content,t('audioOutput'),output);
      const paintDevices=list=>{const outputs=[{id:'default',name:t('defaultOutput')},...(list||[]).filter(d=>(d.id??d.deviceId)!=='default')];options(output,outputs.map(d=>[String(d.id??d.deviceId),String(d.name??d.label??d.id)]),audio.sinkId||'default');if(audio.sinkId&&!outputs.some(d=>(d.id??d.deviceId)===audio.sinkId)){const missing=node('option','',audio.sinkId+' — OFFLINE');missing.value=audio.sinkId;output.append(missing);output.value=audio.sinkId;}};
      paintDevices(audio.outputs||[]);const refresh=async()=>{const r=await invoke('audioList',{},current.feedback);if(r.outputs)paintDevices(r.outputs);};modal.content.append(button(t('refreshAudio'),refresh));const audioButtons=node('div','pt-deck-row');audioButtons.append(button(t('audioSave'),()=>invoke('audioConfigure',{volume:Number(volume.value)/100,sinkId:output.value,sound:sound.value},current.feedback)),button(t('audioTest'),()=>invoke('audioTest',{},current.feedback)));modal.content.append(audioButtons,node('p','pt-deck-help',t('audioHint')));
      const globalLabel=node('label','pt-deck-check pt-deck-divider');const globalInput=node('input');globalInput.type='checkbox';globalInput.checked=!!snapshot.globalHotkeys;globalLabel.append(globalInput,node('span','',t('global')));modal.content.append(globalLabel,node('p','pt-deck-help',t('globalDialogHelp')),node('p','pt-deck-help',t('hotkeyHelp')));current.feedback=node('p','pt-deck-feedback');current.feedback.setAttribute('role','status');modal.content.append(current.feedback);modal.footer.append(button(t('close'),closeSettings),button(t('saveSettings'),()=>invoke('configureHotkeys',{enabled:globalInput.checked},current.feedback),'primary'));modal.close.addEventListener('click',closeSettings);modal.dialog.addEventListener('cancel',event=>{event.preventDefault();closeSettings();});modal.dialog.showModal();await refresh();}
    function closeSettings(){if(!settings)return;const old=settings;settings=null;old.dialog.close();old.dialog.remove();settingsButton.focus();}
    renderStatic();update(adapter.snapshot||{});
    const unsubscribe=typeof adapter.subscribe==='function'?adapter.subscribe(update):null;
    return {update,openEditor,openNumeric,openSettings,setLanguage(value){language=value==='en'?'en':'sr';renderStatic();update({});},destroy(){destroyed=true;unsubscribe?.();if(editor){editor.dialog.remove();editor=null;}if(numeric){numeric.dialog.remove();numeric=null;}if(settings){settings.dialog.remove();settings=null;}host.replaceChildren();}};
  }
  global.ProTimerDeckUI={mount};
})(window);
