const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('pt', {
  deckInvoke: (action, payload) => ipcRenderer.invoke('deck-invoke', action, payload),
  deckFrame: (value) => ipcRenderer.send('deck-frame', value),
  deckDrafts: (value) => ipcRenderer.send('deck-drafts', value),
  deckReply: (value) => ipcRenderer.send('deck-reply', value),
  onDeckRequest: (cb) => ipcRenderer.on('deck-request', (_e, value) => cb(value)),
  onDeckStatus: (cb) => ipcRenderer.on('deck-status', (_e, value) => cb(value)),
  onClockPower: (cb) => ipcRenderer.on('clock-power', (_e, value) => cb(value)),
  sendState: (s) => ipcRenderer.send('state', s),
  onState: (cb) => ipcRenderer.on('state', (e, s) => cb(s)),
  openOutput: (displayId) => ipcRenderer.send('open-output', displayId),
  sendToDisplay: (displayId) => ipcRenderer.send('send-to-display', displayId),
  closeOutput: () => ipcRenderer.send('close-output'),
  toggleFullscreen: () => ipcRenderer.send('toggle-fullscreen'),
  exitFullscreen: () => ipcRenderer.send('exit-fullscreen'),
  resizeOutput: (size) => ipcRenderer.invoke('resize-output', size),
  getOutputGeometry: () => ipcRenderer.invoke('output-geometry'),
  onOutputGeometry: (cb) => ipcRenderer.on('output-geometry', (e, info) => cb(info)),
  openSecondaryOutput: (displayId) => ipcRenderer.invoke('secondary-output-open', displayId),
  closeSecondaryOutput: () => ipcRenderer.send('secondary-output-close'),
  toggleSecondaryFullscreen: () => ipcRenderer.send('secondary-output-fullscreen'),
  getSecondaryOutputGeometry: () => ipcRenderer.invoke('secondary-output-geometry'),
  onSecondaryOutputGeometry: (cb) => ipcRenderer.on('secondary-output-geometry', (e, info) => cb(info)),
  setOnTop: (flag) => ipcRenderer.send('ctl-on-top', flag),
  getDisplays: () => ipcRenderer.invoke('displays'),
  isOutputOpen: () => ipcRenderer.invoke('output-open'),
  getNetworkInfo: () => ipcRenderer.invoke('network-info'),
  checkLocalNetwork: (ip) => ipcRenderer.invoke('check-local-network', ip),
  onDisplays: (cb) => ipcRenderer.on('displays', (e, list) => cb(list)),
  onOutputState: (cb) => ipcRenderer.on('output-state', (e, open) => cb(open)),
  onNetworkInfo: (cb) => ipcRenderer.on('network-info', (e, info) => cb(info)),
  onRemoteCmd: (cb) => ipcRenderer.on('remote-cmd', (e, cmd) => cb(cmd)),
  qr: (text) => ipcRenderer.invoke('qr', text),
  shareStart: () => ipcRenderer.invoke('share-start'),
  shareStop: () => ipcRenderer.invoke('share-stop'),
  shareInfo: () => ipcRenderer.invoke('share-info'),
  onShareInfo: (cb) => ipcRenderer.on('share-info', (e, info) => cb(info)),
  showOutputQr: (payload) => ipcRenderer.invoke('show-output-qr', payload),
  hideOutputQr: () => ipcRenderer.send('hide-output-qr'),
  onOutputQr: (cb) => ipcRenderer.on('output-qr-state', (e, info) => cb(info)),
  onAudienceQr: (cb) => ipcRenderer.on('audience-qr', (e, info) => cb(info)),
  fitWindow: (h) => ipcRenderer.send('fit-window', h),
  onWinFs: (cb) => ipcRenderer.on('win-fs', (e, v) => cb(v))
});
