'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const crypto = require('node:crypto');
const delay = ms => new Promise(resolve => setTimeout(resolve, ms));
// Real Electron renderer + native loopback transport, with a simulated plugin
// HTTP client. This is NOT an Elgato runtime or physical USB test.
module.exports = async function smokeDeck({ controlWin, deckHost, getOutput, getSecondary }) {
  const js = code => controlWin.webContents.executeJavaScript(code);
  for (let n=0;n<100 && !await js('!!deckControl');n++) await delay(50);
  assert.equal(await js('!!deckControl'),true,'Deck controller must mount');
  const base = await js('({s:JSON.parse(JSON.stringify(S)),cues:JSON.parse(JSON.stringify(cues))})');
  const port=await deckHost.bridge.start(), bootstrap=deckHost.bridge.bootstrap();
  let token,sequence=0;
  async function request(route,body){const res=await fetch(`http://127.0.0.1:${port}${route}`,{method:body?'POST':'GET',headers:{...(body?{'Content-Type':'application/json'}:{}),...(token?{Authorization:`Bearer ${token}`}:{})},body:body?JSON.stringify(body):undefined});return res.json();}
  token=(await request('/pair',{nonce:bootstrap.nonce,protocolVersion:1,pluginVersion:'0.1.0'})).token;
  assert.ok(token);
  await request('/inventory',{devices:[{id:'smoke-xl',name:'SIMULATED XL',type:2}],actions:[]});
  const make=(type,timerId='t1',payload={})=>({type,timerId,payload,commandId:crypto.randomUUID(),sequence:++sequence});
  const command=c=>request('/command',{...c,deviceId:'smoke-xl'});
  const state=()=>js('deckControl.model.snapshot()');
  await js("S.dualTimer=true;S.separateOutputs=true;syncDualUI();setDuration(600000);startPause();");
  const before=await js('({endAt:S.endAt,second:JSON.stringify(S.secondary)})');
  assert.equal((await command(make('preset','t1',{durationMs:900000}))).ok,true);
  assert.equal((await command(make('adjust','t1',{step:1,unit:'m',target:'set'}))).ok,true);
  assert.deepEqual(await js('({endAt:S.endAt,second:JSON.stringify(S.secondary)})'),before);
  assert.equal((await state()).timers.t1.draft.durationMs,960000);
  console.log('DECK_ACTIVE_SET_ISOLATION_OK=true');
  let snapshot=await state();
  const replace={...make('startSet'),expectedActiveVersion:snapshot.timers.t1.active.version,expectedDraftVersion:snapshot.timers.t1.draft.version};
  assert.equal((await command(replace)).code,'HOLD_REQUIRED');
  replace.commandId=crypto.randomUUID();replace.sequence=++sequence;
  const press=await request('/press',{command:replace,deviceId:'smoke-xl'});assert.equal(press.ok,true);
  await delay(1550);replace.pressId=press.pressId;
  assert.equal((await command(replace)).ok,true);const deadline=await js('S.endAt');
  assert.equal((await command(replace)).ok,true);assert.equal(await js('S.endAt'),deadline);
  assert.equal(await js('S.durationMs'),960000);
  console.log('DECK_ATOMIC_PROTECTED_START_SET_OK=true');
  assert.equal((await command(make('enterTime','t2'))).ok,true);
  for(const digit of [0,1,2,3,4,5])assert.equal((await command(make('numericDigit','t2',{digit}))).ok,true);
  assert.equal((await command(make('numericApply','t2'))).ok,true);
  snapshot=await state();assert.equal(snapshot.timers.t2.draft.durationMs,5025000);
  assert.equal(await js('S.endAt'),deadline);
  assert.equal((await command({...make('startSet','t2'),expectedActiveVersion:snapshot.timers.t2.active.version,expectedDraftVersion:snapshot.timers.t2.draft.version})).ok,true);
  assert.equal(await js('S.secondary.durationMs'),5025000);
  assert.equal(await js('S.endAt'),deadline);
  console.log('DECK_NUMERIC_T2_012345_OK=true');
  assert.equal((await command(make('countup','t2'))).ok,true);
  assert.equal(await js('S.secondary.mode'),'countdown','SET mode must not change ACTIVE');
  const modes=await js(`(async()=>{
    const start=()=>{const s=deckControl.model.snapshot();return{type:'startSet',timerId:'t2',commandId:crypto.randomUUID(),expectedActiveVersion:s.timers.t2.active.version,expectedDraftVersion:s.timers.t2.draft.version};};
    let c=start();await deckControl.execute(c);let result=await deckControl.execute(c);
    const countup=result.ok&&S.secondary.mode==='countup'&&S.secondary.running;
    await deckControl.execute({type:'clock',timerId:'t2'});c=start();await deckControl.execute(c);result=await deckControl.execute(c);
    return {countup,clock:result.ok&&S.secondary.mode==='clock'&&!S.secondary.running};
  })()`);
  assert.deepEqual(modes,{countup:true,clock:true});assert.equal(await js('S.endAt'),deadline);
  console.log('DECK_T2_COUNTUP_CLOCK_OK=true');
  const reset=await command(make('reset','t2'));assert.equal(reset.code,'HOLD_REQUIRED');
  await deckHost.bridge.close();const activeDeadline=await js('S.endAt');await delay(600);
  assert.equal(await js('S.endAt'),activeDeadline);assert.equal((await state()).editTarget,'set');
  console.log('DECK_DISCONNECT_NO_REPLAY_OK=true');
  await require('./smoke-deck-ui')({controlWin});
  const original=await js('JSON.stringify(S)');
  await js('deckControl.ui.openEditor()');await delay(150);
  assert.equal(await js('document.querySelectorAll(".pt-deck-dialog .pt-deck-key").length'),32);
  assert.equal(await js('JSON.stringify(S)'),original,'Opening editor never changes the engine');
  const image=path.join(os.tmpdir(),'protimer-stream-deck-editor.png');
  fs.writeFileSync(image,(await controlWin.webContents.capturePage()).toPNG());
  console.log('DECK_EDITOR_SCREENSHOT='+image);
  await js("document.querySelector('.pt-deck-dialog').dispatchEvent(new Event('cancel',{cancelable:true}))");
  // Same code path used by a key, applied ACK only after a real output exists.
  const out=await js("applyDeckOperation({type:'outputB',timerId:'t2',action:'open'})");assert.equal(out.ok,true);
  assert.ok(getSecondary());assert.equal(await js('S.endAt'),activeDeadline);
  assert.equal((await js("applyDeckOperation({type:'outputB',timerId:'t2',action:'close'})")).ok,true);
  assert.equal(getSecondary(),null);
  console.log('DECK_REAL_OUTPUT_ADAPTER_OK=true');
  await js(`Object.assign(S,${JSON.stringify(base.s)});cues=${JSON.stringify(base.cues)};syncDualUI();send();updateButtons();renderCues();`);
  console.log('DECK_SMOKE_OK=true');
};
